### ISSUE TITLE
1.7.2 mac遇到顯示問題

### ISSUE THREAD

**Issue by WizardYen** [rayPopo/aio_setting#1]
您好，我有購買您製作的電控盒，使用體驗非常好。
回報一些問題希望能讓您的產品更完善，希望此舉沒有冒犯到您，謝謝
os版本：monterey12.2.1
深色模式下會導致字體是白色，無法看到
轉回淺色模式後則正常
<img width="640" alt="截圖 2022-12-05 上午4 19 35" src="https://user-images.githubusercontent.com/65946544/205513677-987bd224-528d-4c8d-b21a-7afda91b1d9b.png">

**Comment by rayPopo** [comment]
是的，确实有这个问题。但是由于app的背景是一个图片，所以没有办法适应深色模式。

**Comment by WizardYen** [comment]
好的，請問能否在深色模式下，字體顏色仍可維持淺色模式下的顏色呢？謝謝。

**Comment by rayPopo** [comment]
这个我研究一下

**Comment by rayPopo** [comment]
修改 Contents/info.plist配置文件`<dict>`节点加上：
`
<key>NSRequiresAquaSystemAppearance</key>
<true/>
`
接可以避免app进入dark模式了

**Comment by WizardYen** [comment]
已測試成功，非常感謝！
