### ISSUE TITLE
mac 1.7.2 輸入測試打擊鼓面沒有反應 

### ISSUE THREAD

**Issue by WizardYen** [rayPopo/aio_setting#2]
os版本：monterey 12.2.1
使用pc模式與macbook連接後，可以讀取到電路盒內資料。
但打擊測試時沒有反應，連擊數也沒有增加。
開啟記事本打擊鼓面也沒有任何鍵盤輸入。
嘗試使用ios模式，但無法連結電路盒。
<img width="640" alt="截圖 2022-12-06 上午11 10 42" src="https://user-images.githubusercontent.com/65946544/205803067-ad52683b-356e-454f-a0f7-f464f789244e.png">

**Comment by rayPopo** [comment]
首先在第一次启动app时会有一个权限提示，因为app需要键盘输入。在 Security & Privacy -> Input Monitoring 中会看到 aio_gui.1.7.2 ml，这样才能在测试时有反应。

ios模式时，box会模拟为一个midi设备，敲击鼓面会输出midi note。ios版太鼓达人每一次大版本更新时会取消对midi的之后，然后在x.2.0版本会再次加上，比如 5.2.0，但是当前版本是6.0.10，因此还没对midi输入的支持，要等了。

**Comment by rayPopo** [comment]
![4231670320704_ pic](https://user-images.githubusercontent.com/37205327/205879474-cbc6ae53-412d-4f27-8eb1-866f5c46ce43.jpg)

**Comment by rayPopo** [comment]
还有一点从太鼓达人ios版本 6.0 开始必须要联网，而且ios设备的ip必须是日本ip才可以玩。。。
